# docker-compose.yml — Compose 방식(비-Swarm)으로 다중 auth-server 인스턴스 정의
version: "3.7"

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-image
    ports:
      - "9200:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - images-data:/usr/share/nginx/images:ro
    command: [
      "sh", "-c",
      "printf 'upstream profile_upstream {\n    server image-server-1:8080;\n    server image-server-2:8080;\n    server image-server-3:8080;\n}\n\nserver {\n    listen 80;\n    location / {\n        proxy_pass http://profile_upstream;\n        proxy_set_header Host $$host;\n        proxy_set_header X-Real-IP $$remote_addr;\n        proxy_set_header X-Forwarded-For $$proxy_add_x_forwarded_for;\n        proxy_set_header X-Forwarded-Proto $$scheme;\n    }\n}\n' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ]
    depends_on:
      - image-server-1
      - image-server-2
      - image-server-3
    networks:
      - image-network






  # auth-server 인스턴스들을 개별 서비스로 정의 (Compose는 deploy.replicas를 적용하지 않으므로 이렇게 복수 서비스로 표현)
  image-server-1:
    image: ddingsh9/image-server:1.9.1
    env_file:
      - .env.prod
    container_name: image-server-1
    restart: unless-stopped
    networks:
      - image-network
      - infra-network
    volumes:
      - images-data:/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
  image-server-2:
    image: ddingsh9/image-server:1.9.1
    env_file:
      - .env.prod
    container_name: image-server-2
    restart: unless-stopped
    networks:
      - image-network
      - infra-network
    volumes:
      - images-data:/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3

  image-server-3:
    image: ddingsh9/image-server:1.9.1
    env_file:
      - .env.prod
    container_name: image-server-3
    restart: unless-stopped
    networks:
      - image-network
      - infra-network
    volumes:
      - images-data:/uploads

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"


  log-cleaner:
    image: alpine:3.19
    container_name: image-log-cleaner
    restart: unless-stopped
    volumes:
      - /var/log/nginx:/host/nginx/logs:ro
      - ./logs:/host/logs:rw
    command: >
      sh -c "while true; do
        find /host/nginx/logs -type f -name '*.log' -mtime +1 -delete || true;
        find /host/logs -type f -name '*.log' -mtime +1 -delete || true;
        sleep 3600;
      done"

networks:
  image-network:
    driver: bridge
    name: image-network
  infra-network:
    external: true
    name: infra-network

volumes:

  images-data:
    driver: local
    name: images-data
